export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const SELECT_VIDEO_REQUEST = 'SELECT_VIDEO_REQUEST';
export const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS';
export const SELECT_VIDEO_FAIL = 'SELECT_VIDEO_FAIL';

export const LOAD_MORE_VIDEOS_SUCCESS = 'LOAD_MORE_VIDEOS_SUCCESS';

export const AUTH_CALLBACK_RECEIVED = 'AUTH_CALLBACK_RECEIVED';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const GET_VIDEO_RATING_REQUEST = 'GET_VIDEO_RATING_REQUEST';
export const GET_VIDEO_RATING_SUCCESS = 'GET_VIDEO_RATING_SUCCESS';
export const GET_VIDEO_RATING_FAIL = 'GET_VIDEO_RATING_FAIL';

export const RATE_VIDEO_REQUEST = 'RATE_VIDEO_REQUEST';
export const RATE_VIDEO_SUCCESS = 'RATE_VIDEO_SUCCESS';
export const RATE_VIDEO_FAIL = 'RATE_VIDEO_FAIL';
